### ISSUE TITLE
running evilvm in windows

### ISSUE THREAD

**Issue by BEN00262** [jephthai/EvilVM#3]
is it possible to run evilvm natively  on windows

**Comment by jephthai** [comment]
Hmm... I just did a quick test to see how far it would be from running well on Windows.  It's not too bad, actually.  The main thing that doesn't work so well is the build script, because it shells out to bash for a couple things, and the plumbing isn't so good on Windows for that.  

I have a Windows 10 box where I've installed `ruby`, `gcc` from MinGW, `nasm`, and the `git` package that includes normal shell pimitives -- otherwise it's a pretty normal Windows box.  I built the agent manually like this:

    S:\evilvm\agent>nasm -f bin -DIONET -DIPADDR=127,0,0,1 -DPORT=1919 main.asm -o net.shellcode

So this gives me an agent that will connect to localhost on port 1919.  Then I used a shellcode loader to run it (you could just as well use `nasm` to make an object file and link it with MinGW to an EXE).  So then running the server with Win32 ruby, and executing the agent I get something like this:

![image](https://user-images.githubusercontent.com/4597057/59571960-61e9e980-906f-11e9-82a5-27e2cc68663b.png)

This was surprisingly reasonable.  There seem to be a few quirks with `readline` on Win32 Ruby.  And like I said, the build script isn't friendly with Windows yet.  But this is a pretty encouraging result. 

I should add Win32 for the server side, build script, and shims.  Some shims might be hard... but then, some (SMB named pipes) will be easier.  I think this is a good target for improving the project.

**Comment by jephthai** [comment]
I haven't really had any other inquiries about running the EvilVM server on Windows.  It does sort of work, though with some rough edges.  The best strategy is probably to run it in a POSIX-ish environment, like cygwin or with WSL.
