### ISSUE TITLE
Error during build script

### ISSUE THREAD

**Issue by six-pd** [jephthai/EvilVM#4]
Hello!
I've been trying out your tool on my home desktop and it worked perfectly, however, when I switched to my work laptop, I got this error when running the build.rb script:
`x86_64-w64-mingw32-ld: /tmp/object20201004-1631-1m57zw2: file not recognized: file truncated
Traceback (most recent call last):`
`        3: from ./build.rb:421:in '<main>'`
`        2: from ./build.rb:161:in 'compile'`
 `       1: from ./build.rb:150:in 'link'`
`./build.rb:150:in 'read': No such file or directory @ rb_sysopen - /tmp/binary20201004-1631-culhoj (Errno::ENOENT)`

Looks like MinGW is having some trouble but I couldn't figure out why. Do you have any idea what could be causing this? Thanks in advance.

**Comment by jephthai** [comment]
Can you provide your entire `build.rb` line?  The error is because the file to be linked isn't found, so I'm guessing something farther up the chain from mingw is failing.  My best guess would be that `nasm` isn't generating the output successfully.  Are your two systems running the same version of `nasm` (and which one is it?)?

You can get some additional trace messages with `-d` -- that way, you can see exactly what commands are being executed during the build.

**Comment by six-pd** [comment]
I tried checking my `nasm` version and it turns out I didn't have it installed on my laptop... It fixed the issue.
Sorry about that, should have been one of the first things to check, really. It's a fresh install and I just took it for granted.
Either way, thanks for pointing it out. Have a good one!
